name: daily-compose
services:
  daily-db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: daily
      POSTGRES_USER: devteller
      POSTGRES_PASSWORD: devteller123!
    ports:
      - "5432:5432"
  daily-redis:
    image: redis:7.2
    ports:
      - "6379:6379"
